# Neural Network Implementation in Python using SciKit Learn

In [20]:
# load libaries
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
import numpy as np

In [21]:
# load dataset
# Sample Data - (Outlook,Temperature,Humidity,Windy,Play)
dataset = np.array([
		 ['Sunny','Hot','High','False','No'],
		 ['Sunny','Hot','High','True','No'],
		 ['Overcast','Hot','High','False','Yes'],
		 ['Rainy','Mild','High','False','Yes'],
		 ['Rainy','Cool','Normal','False','Yes'],
		 ['Rainy','Cool','Normal','True','No'],
		 ['Overcast','Cool','Normal','True','Yes'],
		 ['Sunny','Mild','High','False','No'],
		 ['Sunny','Cool','Normal','False','Yes'],
		 ['Rainy','Mild','Normal','False','Yes'],
		 ['Sunny','Mild','Normal','True','Yes'],
		 ['Overcast','Mild','High','True','Yes'],
		 ['Overcast','Hot','Normal','False','Yes'],
		 ['Rainy','Mild','High','True','No']
		 ])

In [22]:
# We need to convert categorical data into numerical data for process.
enc = preprocessing.OrdinalEncoder()
enc.fit(dataset)
data = enc.transform(dataset)


In [23]:
print(data)

[[2. 1. 0. 0. 0.]
 [2. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [1. 2. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [2. 2. 0. 0. 0.]
 [2. 0. 1. 0. 1.]
 [1. 2. 1. 0. 1.]
 [2. 2. 1. 1. 1.]
 [0. 2. 0. 1. 1.]
 [0. 1. 1. 0. 1.]
 [1. 2. 0. 1. 0.]]


In [24]:
# Create mapping between Original Target Classes and Encoded Target Classes to show prediction in categorical form.
class_mapping = {}

for num, label in zip((data[:,-1].astype('int')), (dataset[:,-1])):
    class_mapping[num] = label

In [25]:
print(class_mapping)

{0: 'No', 1: 'Yes'}


In [26]:
# Features variables - Taste, Temperature & Texture
features = data[:,0:-1]



In [27]:
print(features)

[[2. 1. 0. 0.]
 [2. 1. 0. 1.]
 [0. 1. 0. 0.]
 [1. 2. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [0. 0. 1. 1.]
 [2. 2. 0. 0.]
 [2. 0. 1. 0.]
 [1. 2. 1. 0.]
 [2. 2. 1. 1.]
 [0. 2. 0. 1.]
 [0. 1. 1. 0.]
 [1. 2. 0. 1.]]


In [28]:
# Target/Dependent Variable - Gender
targets = data[:,-1]

In [29]:
print(targets)

[0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0.]


In [30]:
# Train the Model
model = MLPClassifier(solver='lbfgs', alpha=1e-5)
#fitted  = model.fit(feature_train, target_train)
fitted  = model.fit(features, targets)

In [31]:
#Problem - Should I play if outlook is Sunny, temperature is cool,Humidity is high and windy is true?
guess = np.array([['Sunny','Mild','Normal','False']])

In [32]:
# Predict Play
predictions = fitted.predict( enc.transform(guess) )

In [33]:
#output
predictions_labels = [class_mapping[key] for key in predictions]
print(predictions_labels)


['Yes']
